// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectTracker.Infrastructure;

#nullable disable

namespace ProjectTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251012190752_AddTaskFlowModelsMigration1")]
    partial class AddTaskFlowModelsMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.EmployeeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.ObserverTask", b =>
                {
                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.HasKey("TaskId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("task_observer", (string)null);
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.PerformerTask", b =>
                {
                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.HasKey("TaskId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("task_performer", (string)null);
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.ProjectModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ProjectManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_manager_id");

                    b.Property<long>("TaskFlowId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_flow_id");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("TaskFlowId");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.TaskFlowEdgeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("FromNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_node_id");

                    b.Property<long?>("TaskFlowId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_flow_id");

                    b.Property<long?>("ToNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_node_id");

                    b.HasKey("Id");

                    b.HasIndex("FromNodeId");

                    b.HasIndex("TaskFlowId");

                    b.HasIndex("ToNodeId");

                    b.ToTable("task_flow_edge", (string)null);
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.TaskFlowModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("task_flow", (string)null);
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.TaskFlowNodeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("TaskFlowId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_flow_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskFlowId");

                    b.ToTable("task_flow_node", (string)null);
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.TaskGroupModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("task_group", (string)null);
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.TaskModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long>("TaskFlowNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_flow_node_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskFlowNodeId");

                    b.ToTable("task", (string)null);
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.ObserverTask", b =>
                {
                    b.HasOne("ProjectTracker.Infrastructure.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTracker.Infrastructure.Models.TaskModel", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.PerformerTask", b =>
                {
                    b.HasOne("ProjectTracker.Infrastructure.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTracker.Infrastructure.Models.TaskModel", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.ProjectModel", b =>
                {
                    b.HasOne("ProjectTracker.Infrastructure.Models.EmployeeModel", "Manager")
                        .WithMany("SupervisedProjects")
                        .HasForeignKey("ManagerId");

                    b.HasOne("ProjectTracker.Infrastructure.Models.EmployeeModel", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTracker.Infrastructure.Models.TaskFlowModel", "TaskFlow")
                        .WithMany("Projects")
                        .HasForeignKey("TaskFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("ProjectManager");

                    b.Navigation("TaskFlow");
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.TaskFlowEdgeModel", b =>
                {
                    b.HasOne("ProjectTracker.Infrastructure.Models.TaskFlowNodeModel", "FromNode")
                        .WithMany("FromEdges")
                        .HasForeignKey("FromNodeId");

                    b.HasOne("ProjectTracker.Infrastructure.Models.TaskFlowModel", "TaskFlow")
                        .WithMany("Edges")
                        .HasForeignKey("TaskFlowId");

                    b.HasOne("ProjectTracker.Infrastructure.Models.TaskFlowNodeModel", "ToNode")
                        .WithMany("ToEdges")
                        .HasForeignKey("ToNodeId");

                    b.Navigation("FromNode");

                    b.Navigation("TaskFlow");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.TaskFlowNodeModel", b =>
                {
                    b.HasOne("ProjectTracker.Infrastructure.Models.TaskFlowModel", "TaskFlow")
                        .WithMany("Nodes")
                        .HasForeignKey("TaskFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskFlow");
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.TaskModel", b =>
                {
                    b.HasOne("ProjectTracker.Infrastructure.Models.TaskGroupModel", "TaskGroup")
                        .WithMany("Tasks")
                        .HasForeignKey("GroupId");

                    b.HasOne("ProjectTracker.Infrastructure.Models.ProjectModel", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTracker.Infrastructure.Models.TaskFlowNodeModel", "Status")
                        .WithMany("TaskModels")
                        .HasForeignKey("TaskFlowNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Status");

                    b.Navigation("TaskGroup");
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.EmployeeModel", b =>
                {
                    b.Navigation("ManagedProjects");

                    b.Navigation("SupervisedProjects");
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.ProjectModel", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.TaskFlowModel", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.TaskFlowNodeModel", b =>
                {
                    b.Navigation("FromEdges");

                    b.Navigation("TaskModels");

                    b.Navigation("ToEdges");
                });

            modelBuilder.Entity("ProjectTracker.Infrastructure.Models.TaskGroupModel", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
